# Generated by Django 5.0.4 on 2024-05-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanastrapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='debt_amount',
            new_name='debtAmount',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='debt_due_date',
            new_name='debtDueDate',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='goverment_id',
            new_name='governmentId',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
